logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

#puerto 8590
server:
    port: 8590
spring:

    application:
        name: api-Gateway
    sleuth:
      propagation:
        type: w3c
      trace-id128: true
      supports-join: false

    cloud:
      gateway:
        discovery:
          locator:
            enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://192.168.100.111:8761/eureka/
      fetch-registry: true
      register-with-eureka: true
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970