logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


server:
    port: 8588
spring:
    application:
        name: user-service
    sleuth:
      propagation:
        type: w3c
      trace-id128: true
      supports-join: false

    datasource: #postgres database configuration
        url: jdbc:postgresql://192.168.100.111:5432/gym_authentication
        username: postgres
        password: password123
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create #colocar none cuando ya se haya creado la base de datos
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://192.168.100.111:8761/eureka/
      fetch-registry: true
      register-with-eureka: true
jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000
